### ISSUE TITLE
Native interop

### ISSUE THREAD

**Issue by buybackoff** [adamcaudill/libsodium-net#97]
I cannot make the tests passing on my machine, they all fail on [this line](https://github.com/adamcaudill/libsodium-net/blob/master/libsodium-net/Utilities.cs#L121). `bin` is zero after calling 
```
var ret = SodiumLibrary.sodium_hex2bin(bin, arr.Length, hex, hex.Length, IGNORED_CHARS, out binLength, null);
```

In general, why are you using DynamicInvoke and native delegates instead of conventional P/Invoke with DllImport? There is a big overhead on each call to native - and both DynamicInvoke and native delegates add to it. See http://stackoverflow.com/a/12858434/801189 and http://stackoverflow.com/q/27981719/801189

Libsodium must be very fast especially for streaming, but current interop just kills the performance. I haven't done test because I cannot run the current code, but I could reason that this overhead for e.g. encrypting thousands of small byte[] buffers is huge.

**Comment by deckar01** [comment]
This comment seems to provide a good solution:

> I handle that by calling `LoadLibrary` before any other p/invoke call passing the full path to the correct bitness DLL. From there on in, the p/invoke calls that refer to the DLL with just the DLL name bind to the module that is already loaded. Best of both worlds.

It's worth a try.

**Comment by deckar01** [comment]
It turns out `LoadLibrary` is in `kernel32.dll`, and I'm not convinced dynamically loading `libdl.so` is the right path to go down.

A simpler solution seems to be adding a post-build event that copies the DLLs to separate "x86" and "x64" directories both named "libsodium.dll". This would allow us to completely remove the dynamic/lazy invoke and fall back to the standard `DllImport` attribute. The only thing left to do is to make sure we specify the correct DLL directory before the first external function is called. Appending it to the PATH in a static constructor for `SodiumLibrary` seems like the simplest solution.

I'm not sure how this will interact with mono though. If I understand how the dllmap works, we can safely `[DllImport('libsodium.dll')]`, because the `Sodium.dll.config` will handle the mapping for OSX and Linux. Anyone know? I should probably test this, but the easiest way for me to test against these platforms is TravisCI.

**Comment by buybackoff** [comment]
Have a look at this: https://github.com/Spreads/Bootstrapper (it is extracted from Yeppp)

**Comment by adamcaudill** [comment]
> A simpler solution seems to be adding a post-build event that copies the DLLs to separate "x86" and "x64" directories both named "libsodium.dll". 

One thing we should do is make sure that we minimize the complications for users - this is a library to be used in applications or other libraries, so we want to make sure that we are keeping things as simple as possible. Adding two additional directories has an impact on how applications are deployed, perhaps a small impact, but it's something that *will* impact *all* users - direct or indirect.

Because of the performance impact, I'm certainly open to changing how we do this, I just want to make sure that we are careful about the impact.

**Comment by deckar01** [comment]
Now that I have DllImport working I am evaluating the original comment:
> In general, why are you using DynamicInvoke and native delegates instead of conventional P/Invoke with DllImport? There is a big overhead on each call to native ...

I am testing 5,000,000 iterations of `SodiumLibrary.randombytes_uniform()`.
master: ~3.7972172s
pinvoke: ~3.7142125s (-2.2%)
suppressed security: ~3.7312134s on my machine. (-1.7%)

I guess the question is now, does a 2.2% speedup justify changing the way the DLLs are distributed and testing it across all the platforms. My guess is no. @adamcaudill Thoughts?

There does not seem to be "a big overhead on each call to native" considering that 2.2% represents ~17ns per call.

@buybackoff Are your tests still failing on `SodiumLibrary.sodium_hex2bin`? Additional info about your OS and architecture will help determine the issue.

**Comment by buybackoff** [comment]
@deckar01 the last time I tried was one year ago, I decided to use native libs directly with the Bootstrapper template.

**Comment by deckar01** [comment]
Awesome! Glad to hear you used libsodium in your project.

If you would still like me to look into your issue let me know your OS details.

**Comment by buybackoff** [comment]
Win 7, .NET 4.5

**Comment by adamcaudill** [comment]
@deckar01 Thanks! I really appreciate you taking the time to get the numbers. Based on these results, I think it's safe to say that the overhead is low enough that it doesn't justify the impact of changing it.

**Comment by deckar01** [comment]
I'm unable to reproduce the issue using Windows 7 and targeting .NET 4.5 (x86).
